baseURL = 'https://noahmichaels.xyz/'
languageCode = 'en-us'
title = 'Noah Michaels'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Résumé'
pageRef = '/résumé'
weight = 20

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 30

[security]
  enableInlineShortcodes = true

[params]
  description = "Noah Michaels is a graphic designer and print production specialist based in Raleigh, NC."
